(function() {var implementors = {};
implementors["rand"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"rand/rngs/struct.EntropyRng.html\" title=\"struct rand::rngs::EntropyRng\">EntropyRng</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"rand/rngs/struct.ThreadRng.html\" title=\"struct rand::rngs::ThreadRng\">ThreadRng</a>",];
implementors["secp256k1"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"secp256k1/struct.Secp256k1.html\" title=\"struct secp256k1::Secp256k1\">Secp256k1</a>&lt;<a class=\"enum\" href=\"secp256k1/enum.All.html\" title=\"enum secp256k1::All\">All</a>&gt;",synthetic:false,types:["secp256k1::Secp256k1"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"secp256k1/ffi/struct.PublicKey.html\" title=\"struct secp256k1::ffi::PublicKey\">PublicKey</a>",synthetic:false,types:["secp256k1::ffi::PublicKey"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"secp256k1/ffi/struct.Signature.html\" title=\"struct secp256k1::ffi::Signature\">Signature</a>",synthetic:false,types:["secp256k1::ffi::Signature"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"secp256k1/ffi/struct.SharedSecret.html\" title=\"struct secp256k1::ffi::SharedSecret\">SharedSecret</a>",synthetic:false,types:["secp256k1::ffi::SharedSecret"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"secp256k1/struct.SerializedSignature.html\" title=\"struct secp256k1::SerializedSignature\">SerializedSignature</a>",synthetic:false,types:["secp256k1::SerializedSignature"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()